import { chromium } from 'playwright'
const OUT = process.argv[2]
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 430, height: 760 }, deviceScaleFactor: 2, colorScheme: 'light' })
const page = await ctx.newPage()
await page.goto('http://localhost:5180/', { waitUntil: 'networkidle', timeout: 60000 }).catch(() => {})
await page.waitForSelector('.maplibregl-canvas', { timeout: 30000 }).catch(() => {})
await page.waitForTimeout(6000)
await page.locator('.panel__handle').click().catch(() => {})
await page.waitForTimeout(300)
await page.locator('.quick-action--primary').click()
await page.waitForTimeout(400)
await page.locator('.picker__chip').first().click()
await page.waitForTimeout(300)
await page.locator('.picker__input').fill('hal')
await page.waitForTimeout(700)
await page.screenshot({ path: `${OUT}/picker-open.png` })
console.log('done')
await browser.close()
